### ISSUE TITLE
Statistics for Publisher about Speakers

### ISSUE THREAD

**Issue by m--i** [TEQST/TEQST#12]
Export a *list of users* as csv-File which have participated in any of a user's SharedFolders.

Information per user:
- Username
- E-Mail
- Country
- Total data [min,decimal]
- Total recording time with rerecording [min, decimal]
- Last change (recording) [DateTime]

Additionally, for each user row there should be a column for each SharedFolder:
- Completely finished texts in this SharedFolder [%]
- Total data time [min, decimal]
- Total Time spent recording [min, decimal]

**Comment by Doomse** [comment]
Depends on #4

**Comment by YAWNICK** [comment]
Concerning the additional process columns for each sharedfolder: 
What should be the header for each column? If it's just the name, then it's possibly not unique, because sharedfolders which have different parent folders could have same names. Alternatively I could make the path the header (i.e. "jannik/stories/hobbit"), however this could be inconvenient when looking at the file in excel, because the columns need to be made wider to see the entire sharedfolder path, which means more scrolling to the right...
