### ISSUE TITLE
Token management

### ISSUE THREAD

**Issue by YAWNICK** [TEQST/TEQST#13]
Measures to make the token management better

- [x] be able to notify user if they forgot to log out or create some mechanism which prohibits a user from using the same token for a longer period of time (multiple sessions)

**Comment by Doomse** [comment]
What exactly is this endpoint supposed to do? Checking the validity of a token can simply be done by making a GET request against any basic endpoint (like `/api/user/`) and checking the status code for 200 or 401. One could even do a HEAD request against the same endpoint in order to not transmit userdata

**Comment by YAWNICK** [comment]
The idea is to be able to alert the user upon login if they forgot to log out (i.e. their token still exists). Maybe a separate endpoint is unnecessary for this. I'll edit my original comment. At this point I think it might be a good solution to include this info in the answer of the standard login request.
